<a href="https://colab.research.google.com/github/suyeon1109/cornell-lost-ladybug-project/blob/main/data_reorganize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
from tensorflow.keras.layers import TextVectorization, CategoryEncoding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load your CSV data into a DataFrame (replace this with your data loading code)
data1 = pd.read_csv('/content/train (1).csv')
data2 = pd.read_csv('/content/test.csv')
data = pd.concat([data1, data2], axis=0)
data = data.reset_index(drop=True)
# train.stack(data2, level=-1, dropna=True)

# data['array'] = data['array'].str.replace('.', ',')
# data['array'] = data['array'].str.replace('\n', ',')
# data['array'] = data['array'].str.replace(',,', '..')
# data['array'] = data['array'].str.replace(',,,', '...')
# data['array'] = data['array'].str.replace(',,,,', '....')
# data['array'] = data['array'].str.replace(',,,,,', '.....')
# data['array'][0]

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Preprocess the 'stateName' column using tokenization and padding
max_words = 1000  # Maximum number of words to consider
max_sequence_length = 10  # Maximum length of a sequence
tokenizer = Tokenizer(num_words=max_words, oov_token='<OOV>')  # <OOV> for out-of-vocabulary words
tokenizer.fit_on_texts(data['stateName'])
sequences = tokenizer.texts_to_sequences(data['stateName'])
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length, padding='post', truncating='post')

# # Separate features and labels
# features = padded_sequences
# labels = data['target_column']

In [25]:
data = data.drop('Unnamed: 0.1', axis=1)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7659 entries, 0 to 7658
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                7659 non-null   int64  
 1   imageFileName             7659 non-null   object 
 2   array                     7659 non-null   object 
 3   photoSubmissionID         7659 non-null   int64  
 4   speciesName               7659 non-null   object 
 5   isGuess                   7659 non-null   object 
 6   photoQuality              7659 non-null   object 
 7   year                      7659 non-null   int64  
 8   stateName                 7659 non-null   object 
 9   countyName                7659 non-null   object 
 10  tribalLand                7659 non-null   object 
 11  latitude                  7659 non-null   object 
 12  longitude                 7659 non-null   object 
 13  spotterNumber             7659 non-null   int64  
 14  habitatN

In [27]:
# Iterate through columns with string values and convert them to int64
for column in data.columns:
    if data[column].dtype == 'object':  # Check if column contains string values
        data[column] = data[column].astype('int64', errors='ignore')

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7659 entries, 0 to 7658
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                7659 non-null   int64  
 1   imageFileName             7659 non-null   object 
 2   array                     7659 non-null   object 
 3   photoSubmissionID         7659 non-null   int64  
 4   speciesName               7659 non-null   object 
 5   isGuess                   7659 non-null   object 
 6   photoQuality              7659 non-null   object 
 7   year                      7659 non-null   int64  
 8   stateName                 7659 non-null   object 
 9   countyName                7659 non-null   object 
 10  tribalLand                7659 non-null   object 
 11  latitude                  7659 non-null   object 
 12  longitude                 7659 non-null   object 
 13  spotterNumber             7659 non-null   int64  
 14  habitatN

In [30]:
from sklearn.datasets import load_iris
from sklearn import preprocessing

load = load_iris()

# separate the independent and dependent variables
X_data = load.data
target = load.target

# standardization of dependent variables
standard = preprocessing.scale(X_data)
print(standard)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [13]:
# Convert string values in 'array' column to numpy arrays
for idx, row in data.iterrows():
    string_array = row['array']  # Get the string value from the 'array' column
    numpy_array = np.fromstring(string_array[1:-1], sep=',', dtype=np.float32)  # Convert to numpy array
    data.at[idx, 'array'] = numpy_array  # Update the DataFrame with the numpy array


from tensorflow.keras.utils import to_categorical
from ast import literal_eval  # Used to convert string list to actual list

# Convert the string list column to actual lists
data['stateName'] = data['stateName'].apply(lambda x: literal_eval(x))

# Separate features and labels
features = data.drop('array', axis=1)
labels = data['array']

# Convert string categories to numerical labels if needed
# Example: if 'target_column' contains string labels
# labels = pd.Categorical(labels).codes

# Convert the list column to numpy arrays
list_column_array = np.array(features['array'].tolist())

# Drop the original list column from features
features = features.drop('array', axis=1)

# Convert categorical variables to one-hot encodings if needed
# features = pd.get_dummies(features, columns=['categorical_column'])

# Create the Keras model
model = Sequential([
    Dense(64, activation='relu', input_shape=(features.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')  # Change activation based on your problem
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(features, labels, epochs=10, batch_size=32, validation_split=0.2)


ValueError: ignored

In [105]:
data['array']

0       [[[115. 102. 112.]\n  [110. 110. 108.]\n  [ 50...
1       [[[ 77.  89.  85.]\n  [ 85.  96.  98.]\n  [ 96...
2       [[[119. 154.  70.]\n  [124. 162.  75.]\n  [116...
3       [[[ 69.  47.  34.]\n  [ 69.  47.  34.]\n  [ 69...
4       [[[108.  73.  31.]\n  [113.  72.  42.]\n  [107...
                              ...                        
7654    [[[185. 208. 226.]\n  [222. 235. 244.]\n  [253...
7655    [[[184. 133. 130.]\n  [186. 135. 132.]\n  [185...
7656    [[[168. 186. 208.]\n  [164. 182. 204.]\n  [167...
7657    [[[105.  73.  52.]\n  [107.  75.  54.]\n  [103...
7658    [[[ 95. 123.  38.]\n  [ 86. 114.  29.]\n  [ 88...
Name: array, Length: 7659, dtype: object

In [5]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from ast import literal_eval  # Used to convert string list to actual list

# Convert the string list column to actual lists
data['countyName'] = data['countyName'].apply(lambda x: literal_eval(x))

# Separate features and labels
features = data.drop('array', axis=1)
labels = data['array']

# Convert string categories to numerical labels if needed
# Example: if 'target_column' contains string labels
# labels = pd.Categorical(labels).codes

# Convert the list column to numpy arrays
list_column_array = np.array(features['array'].tolist())

# Drop the original list column from features
features = features.drop('array', axis=1)

# Convert categorical variables to one-hot encodings if needed
# features = pd.get_dummies(features, columns=['categorical_column'])

# Create the Keras model
model = Sequential([
    Dense(64, activation='relu', input_shape=(features.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='linear')  # Change activation based on your problem
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(features, labels, epochs=10, batch_size=32, validation_split=0.2)


ValueError: ignored

In [106]:
import pandas as pd
import numpy as np
from tensorflow.keras.layers import TextVectorization, CategoryEncoding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load your CSV data into a DataFrame (replace this with your data loading code)
data1 = pd.read_csv('/train (1).csv')
data2 = pd.read_csv('/test.csv')
data = pd.concat([data1, data2], axis=0)
data = data.reset_index(drop=True)
# train.stack(data2, level=-1, dropna=True)

data['array'] = data['array'].str.replace('.', ',')
data['array'] = data['array'].str.replace('\n', ',')

data['array'] = data['array'].str.replace(',,', '..')
data['array'] = data['array'].str.replace(',,,', '...')
data['array'] = data['array'].str.replace(',,,,', '....')
data['array'] = data['array'].str.replace(',,,,,', '.....')
data['array'][0]

# Identify object and string columns you want to convert
# obj_to_str_columns = ['imageFileName', 'speciesName', 'isGuess', 'photoQuality',
#        'stateName', 'countyName', 'tribalLand','habitatName', 'timeOfDay',
#        'searchPlanned', 'method', 'weather', 'foundBugs', 'hasplant',
#        'Educational: egg', 'Educational: prey', 'Educational: larva',
#        'Educational: aggregation', 'Educational: pupa', 'Educational: not ladybug',
#        'Other: kids', 'Other: story', 'Other: rare', 'Other: out NAm',
#        'Other: Host Plant ID', 'Source: Kids', 'Source: Youth (14-23)',
#        'Source: Adult', 'Source: Group','Source: Family', 'latitude',
#        'longitude', 'temperature']

str_to_int_columns = ['latitude', 'longitude', 'temperature']

# object_columns = data.select_dtypes(include=['object'])

# for column_name in obj_to_str_columns:
#     data[column_name] = pd.factorize(data[column_name])[0].astype(str)

for each in str_to_int_columns:
    data[each] = pd.to_numeric(data[each], errors='coerce').astype('Float64')


# object_columns = data.select_dtypes(include=['object'])

# for column_name in object_columns:
#     counter = 0
#     for unique_value in data[column_name].unique().tolist():
#         data.loc[data[column_name] == unique_value, column_name] = str(counter)
#         counter += 1
'''
지금 문제점:
1. array column 밑의 값들이
'''

# Convert numpy array values to formatted strings
formatted_array_data = []
for array in data['array']:
    formatted_array = array.tolist()  # Convert numpy array to list and then to string
    formatted_array_data.append(formatted_array)

# Update the 'array' column in the DataFrame with formatted values
data['array'] = formatted_array_data

# Save the DataFrame back to the CSV file
data.to_csv('updated_data.csv', index=False)

<ipython-input-106-d24715030fbf>:14: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data['array'] = data['array'].str.replace('.', ',')


AttributeError: ignored

In [25]:
data['array']

0       [[[115, 102, 112,],  [110, 110, 108,],  [ 50, ...
1       [[[ 77,  89,  85,],  [ 85,  96,  98,],  [ 96, ...
2       [[[119, 154,  70,],  [124, 162,  75,],  [116, ...
3       [[[ 69,  47,  34,],  [ 69,  47,  34,],  [ 69, ...
4       [[[108,  73,  31,],  [113,  72,  42,],  [107, ...
                              ...                        
6067    [[[102, 111, 126,],  [ 94, 103, 118,],  [ 93, ...
6068    [[[169, 113, 116,],  [167, 111, 114,],  [183, ...
6069    [[[201, 184, 164,],  [202, 185, 165,],  [198, ...
6070    [[[210, 151, 153,],  [201, 142, 144,],  [200, ...
6071    [[[184, 150, 148,],  [184, 150, 148,],  [183, ...
Name: array, Length: 6072, dtype: object

In [56]:
import os
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.utils import shuffle
from tensorflow.keras.utils import to_categorical
from ast import literal_eval

# # Load CSV data into a DataFrame
# csv_file_path = '/train (1).csv'  # Replace with the actual file path
# data = pd.read_csv(csv_file_path)

# Add a vacant column (replace 'new_column_name' with the desired column name)
data['label'] = ''
# Save the DataFrame back to the CSV file
data.to_csv('updated_data.csv', index=False)

# Define other parameters
sample_num = 22

# Preprocess data
label_encoder = LabelEncoder()

images = []
labels = []

for idx, row in data.iterrows():
    # Process image data (assuming image array column name is 'array')
    img_array = literal_eval(row['array'])

    # Process string data (assuming string column name is 'speciesName')
    string_value = row['speciesName']
    categorical_value = label_encoder.fit_transform([string_value])[0]

    # Combine all processed features into a single input vector
    input_vector = [img_array, categorical_value]

    images.append(input_vector)
    labels.append(row['label'])  # Assuming you have a 'label' column in your CSV

# Convert lists to numpy arrays
images = np.array(images)
labels = np.array(labels)

# Shuffle the data
images, labels = shuffle(images, labels)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# Build the model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(images.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(label_encoder.classes_.shape[0], activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, to_categorical(y_train), epochs=10, batch_size=100)

# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, to_categorical(y_test))
print('test_acc:', test_acc)
print('test_loss:', test_loss)

ValueError: ignored

In [9]:
import os
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.utils import shuffle
from tensorflow.keras.utils import to_categorical
from ast import literal_eval

# Load CSV data into a DataFrame
csv_file_path = '/train (1).csv'  # Replace with the actual file path
data = pd.read_csv(csv_file_path)
# Add a vacant column (replace 'new_column_name' with the desired column name)
data['label'] = ''
# Save the DataFrame back to the CSV file
data.to_csv('updated_data.csv', index=False)

# Define other parameters
sample_num = 22

# Preprocess data
label_encoder = LabelEncoder()
scaler = MinMaxScaler()

images = []
labels = []

for idx, row in data.iterrows():
    # Process image data (assuming image array column name is 'array')
    # img_array = ast.literal_eval(row['array'][1:-1], sep=',')
    img_array = literal_eval(row['array'])

    # Process string data (assuming string column name is 'speciesName')
    string_value = row['speciesName']
    categorical_value = label_encoder.fit_transform([string_value])[0]

    # Process float data (assuming float column name is 'longitude')
    # float_value = row['longitude']
    # scaled_float = scaler.fit_transform(np.array([[float_value]]))

    # Combine all processed features into a single input vector
    input_vector = np.concatenate([img_array, [categorical_value], scaled_float.flatten()])

    images.append(input_vector)
    labels.append(row['label'])  # Assuming you have a 'label' column in your CSV

# Convert lists to numpy arrays
images = np.array(images)
labels = np.array(labels)

# Shuffle the data
images, labels = shuffle(images, labels)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

# Build the model
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(images.shape[1],)))
model.add(Dense(32, activation='relu'))
model.add(Dense(label_encoder.classes_.shape[0], activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, to_categorical(y_train), epochs=10, batch_size=100)

# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, to_categorical(y_test))
print('test_acc:', test_acc)
print('test_loss:', test_loss)

SyntaxError: ignored

In [ ]:
import os
import random
import numpy as np
from keras.preprocessing import image
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
import tensorflow as tf
import matplotlib.pyplot as plt
import keras.utils as image



# Load CSV data into a DataFrame
csv_file_path = '/content/train (1).csv'  # Replace with the actual file path
data = pd.read_csv(csv_file_path)
# Add a vacant column (replace 'new_column_name' with the desired column name)
data['label'] = ''
# Save the DataFrame back to the CSV file
data.to_csv('updated_data.csv', index=False)

# Mount Google Drive to access the dataset
from google.colab import drive
drive.mount('/content/drive')

# Define the paths to your dataset folders and other parameters
data_dir = '/content/train (1).csv'
train_ratio = 0.8
image_size = (224, 224)  # Adjust the image size as needed
sample_num = 1000

# Create a dictionary to map label names to numeric labels
label_mapping = {}
label_counter = 0

# Initialize empty lists to store images and labels
train_images = []
train_labels = []
test_images = []
test_labels = []

# Iterate through each subfolder (label) in the dataset directory
for label in os.listdir(data_dir):
    label_dir = os.path.join(data_dir, label)

    # Check if the label folder has at least 111 images
    if len(os.listdir(label_dir)) >= sample_num:
        image_paths = os.listdir(label_dir)

        # If there are more than 112 images, randomly select 112 images
        if len(image_paths) > sample_num:
            image_paths = random.sample(image_paths, sample_num)

        # Assign a numeric label and update the mapping
        if label not in label_mapping:
            label_mapping[label] = label_counter
            label_counter += 1

        numeric_label = label_mapping[label]

        # Calculate the number of images for training and testing
        num_train = int(len(image_paths) * train_ratio)

        # Iterate through the selected image paths
        for idx, img_path in enumerate(image_paths):
            img = image.load_img(os.path.join(label_dir, img_path), target_size=image_size)
            img_array = image.img_to_array(img)
            img_array = img_array / 255.0  # Normalize pixel values

            if idx < num_train:
                train_images.append(img_array)
                train_labels.append(numeric_label)
            else:
                test_images.append(img_array)
                test_labels.append(numeric_label)

# Convert lists to numpy arrays
train_images = np.array(train_images)
train_labels = np.array(train_labels)
test_images = np.array(test_images)
test_labels = np.array(test_labels)

# (1) 모델 설정
# 딥러닝의 구조와 층을 설정하는 단계
network = Sequential()
network.add(Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)))
network.add(MaxPooling2D((2, 2)))
network.add(Conv2D(64, (3, 3), activation='relu'))
network.add(MaxPooling2D((2, 2)))
network.add(Conv2D(128, (3, 3), activation='relu'))
network.add(Flatten())
network.add(Dense(label_counter, activation='softmax'))

network.compile(optimizer='adam',
                loss='categorical_crossentropy',
                metrics=['accuracy'])

# (3) 모델 학습 (실행)
network.fit(train_images, to_categorical(train_labels), epochs=10, batch_size=100)

# (4) 모델 평가(결과 출력)
test_loss, test_acc = network.evaluate(test_images, to_categorical(test_labels))
print('test_acc:', test_acc)
print('test_loss:', test_loss)

# Visualize misclassified samples
for x in range(500):
    image = test_images[x, :].reshape(1, 224, 224, 3)
    prediction = network.predict(image).argmax()
    label = test_labels[x]
    if prediction != label:
        plt.title("Sample %d  Prediction: %d Label: %d" % (x, prediction, label))
        plt.imshow(image.reshape([224, 224, 3]), cmap=plt.get_cmap('gray_r'))
        plt.show()